using TMPS.Domain.Models.Abstractions;

namespace TMPS.Domain.Models.Reports;


public static class ReportPrototypes
{
    public static Report DefaultReport(Employee employee)
    {
        return new Report(
            $"Report for {employee.Name}",
            $"This is a report for {employee.Name}",
            $"Report generated by {employee.Name}"
        );
    }

    public static Report DetailedReport(Employee employee)
    {
        return new Report(
            $"Detailed report for {employee.Name}",
            $"This is a detailed report for {employee.Name}",
            $"Detailed report generated by {employee.Name}"
        );
    }

    public static Report ProgressReport(Employee employee)
    {
        return new Report(
            $"Progress report for {employee.Name}",
            $"This is a progress report for {employee.Name}",
            $"Progress report generated by {employee.Name}"
        );
    }

}
